export const pdpQueryParams = {
  'populate[0]': 'SEO',
  'populate[1]': 'heroSection.image',
  'populate[2]': 'heroSection.benefits',
  'populate[3]': 'sectionOne',
  'populate[4]': 'enumerationOne',
  'populate[5]': 'sectionTwo',
  'populate[6]': 'popularDestinations',
  'populate[7]': 'spliterSectionOne.cta',
  'populate[8]': 'spliterSectionOne.image',
  'populate[9]': 'sectionThree',
  'populate[10]': 'enumerationTwo',
  'populate[11]': 'priceSection.cta',
  'populate[12]': 'spliterSectionTwo.cta',
  'populate[13]': 'spliterSectionTwo.image',
  'populate[14]': 'sectionFour',
  'populate[15]': 'dailyRoutes',
  'populate[16]': 'spliterThree.cta',
  'populate[17]': 'spliterThree.image',
  'populate[18]': 'otherBuses',
};
