export const pdpQueryParams = {
  'populate[0]': 'SEO',
  'populate[1]': 'heroSection.image',
  'populate[2]': 'heroSection.benefits',
  'populate[3]': 'sectionOne',
  'populate[4]': 'enumerationOne',
  'populate[5]': 'sectionTwo',
  'populate[6]': 'popularDestinations',
  'populate[7]': 'separatorSectionOne.cta',
  'populate[8]': 'separatorSectionOne.image',
  'populate[9]': 'sectionThree',
  'populate[10]': 'enumerationTwo',
  'populate[11]': 'priceSection.cta',
  'populate[12]': 'separatorSectionTwo.cta',
  'populate[13]': 'separatorSectionTwo.image',
  'populate[14]': 'sectionFour',
  'populate[15]': 'dailyRoutes',
  'populate[16]': 'separatorSectionThree.cta',
  'populate[17]': 'separatorSectionThree.image',
  'populate[18]': 'otherBuses',
  'populate[19]': 'routes',
  'populate[20]': 'routes.from',
  'populate[21]': 'routes.to',
  'populate[22]': 'tags',
  'populate[23]': 'tags.tag',
};

export const homeQueryParams = {
  'populate[0]': 'SEO',
  'populate[1]': 'heroSection',
  'populate[2]': 'intro',
  'populate[3]': 'sectionTwo',
  'populate[4]': 'cards',
  'populate[5]': 'cards.image',
  'populate[6]': 'cards.tags',
  'populate[7]': 'cards.cta',
  'populate[8]': 'separatorOne.cta',
  'populate[9]': 'separatorOne.image',
  'populate[10]': 'separatorTwo.cta',
  'populate[11]': 'separatorTwo.image',
};
